### ISSUE TITLE
Label and README Github action fails for Pull Requests from external forks into Develop

### ISSUE THREAD

**Issue by Azd325** [bank2ynab/bank2ynab#419] opened 2022-04-04 16:49 UTC
Are there any project specific settings that you block external actions?

On my fork, the label and README action run through. https://github.com/Azd325/bank2ynab/pull/1

https://github.com/Azd325/bank2ynab/actions/runs/2091241892
https://github.com/Azd325/bank2ynab/actions/runs/2091241890

Screenshot from the settings page.
<img width="772" alt="Screen Shot 2022-04-04 at 18 48 56" src="https://user-images.githubusercontent.com/426541/161592799-967301a5-4bac-4ae9-90cb-749d99385db0.png">

**Comment by nocalla** [comment] 2022-04-04 21:12
No, the same settings apply. I think the issue is that the Action is owned by the branch it is being merged into, which doesn't have permissions to modify the source branch. I can't seem to find an option to check the ownership of the branch prior to running the branch. Something like `if external fork: don't run action` at the top, would be the ideal.

**Comment by Azd325** [comment] 2022-04-05 06:05
I see. It seems that has to do with this 

> Warning: For workflows that are triggered by the pull_request_target event, the GITHUB_TOKEN is granted read/write repository permission unless the permissions key is specified and the workflow can access secrets, even when it is triggered from a fork. Although the workflow runs in the context of the base of the pull request, you should make sure that you do not check out, build, or run untrusted code from the pull request with this event. Additionally, any caches share the same scope as the base branch. To help prevent cache poisoning, you should not save the cache if there is a possibility that the cache contents were altered. For more information, see "[Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)" on the GitHub Security Lab website.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target


I tried to update the label workflow so we can figure out if has to do with it but I think need to be approved of you or merged that it runs.
https://github.com/bank2ynab/bank2ynab/pull/420 


For the updating README workflow what you hink about after this https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

**Comment by nocalla** [comment] 2022-04-05 20:28
Merged #420 so we can see if that helps. The Github Actions documentation is so hard to navigate - I wasn't even aware there was a permissions section we could use!

**Comment by nocalla** [comment] 2022-04-05 20:29
```
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```

This seems like it would make a lot of sense (as well as for running the Black auto-fixing, since that hits the same limitations).

**Comment by Azd325** [comment] 2022-04-06 16:33
Label workflow seems to work after the change. 
Example PR https://github.com/bank2ynab/bank2ynab/pull/421

**Comment by nocalla** [comment] 2022-04-06 20:18
Great!

**Closed** 2023-02-04 22:22 UTC
