### ISSUE TITLE
SyntaxWarning @ line 269, 270, 322

### ISSUE THREAD

**Issue by ferryrs** [bank2ynab/bank2ynab#298] opened 2019-11-02 13:20 UTC
**Describe the bug**
Used the following line in terminal:
python3 ./bank2ynab.py
Got this error:
./bank2ynab.py:269: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if filepath is "":
./bank2ynab.py:270: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if os.name is "nt":
./bank2ynab.py:322: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if file_pattern is not "":
INFO 
Done! 0 files processed.

**What did you EXPECT to happen?**
A working file.

**What ACTUALLY happened?**
Terminal error.

**What did you DO? (steps to reproduce)**
1. Double-checked file pathway and configuration.
2. Double-checked if bank is listed and the right .CSV filename format is being used as stated in: bank2ynab.conf.
3. Double checked every single step in Readme and tried it multiple times over and over.
4. Searched on internet.

**What's your software environment?**
 - Script language: Python 3.8.0
 - Operating system: MacOS
 - OS version: Mojave 10.14.6

**Comment by nocalla** [comment] 2019-11-03 16:44
So this is an interesting one - our automated checks look at the nightly Python release, so 3.8 should be accounted for, I'll add 3.8 to the checks manually and see if it throws an error. Either way, these are syntax warnings rather than a flat-out error, so the program should still run. I'll update the code to what the compiler is recommending anyway - I think these are some of the oldest unchanged lines in the code!

**Comment by nocalla** [comment] 2019-11-03 16:56
Hi @ferryrs - can you try to use the develop branch code and see if that fixes your issue? The master code is long overdue an update so it looks like this syntax error has actually been fixed in the develop branch. You can download it from the main front page of the project (the Clone or Download button).

**Comment by nocalla** [comment] 2019-11-03 16:57
Confirmed that this issue is with the `master` branch only and has been fixed in `develop`. Will be pushed to master with next version bump.

**Closed by nocalla** 2019-11-03 16:57 UTC

**Comment by ferryrs** [comment] 2019-11-03 21:24
Just tried to use the develop branch code. Got this error now:

Traceback (most recent call last):
File "./bank2ynab.py", line 28, in <module>
import requests
ModuleNotFoundError: No module named 'requests'

**Comment by nocalla** [comment] 2019-11-03 21:56
So that means you're missing one of the dependencies for the code to work. If you have pip installed, which I think is default for newer Python installs, you can use "pip install -r requirements.txt -f " to install all dependencies.

**Comment by ferryrs** [comment] 2019-11-04 21:35
After doing 'cd' to the location and entering that command directly into to the terminal I get: "-bash: pip: command not found"
When I first do 'python3' and then the command stated above I get: "
ip install -r requirements.txt -f
  File "<stdin>", line 1
    pip install -r requirements.txt -f
        ^
SyntaxError: invalid syntax"

Please advice
